port: 8081

fileStorage:
    path: data/audio.in/

messageServer: 
    broker: amqp://list:list@localhost:5672/
    
mongo:
    url: localhost:27018


logger:
    level: info
    formatter:
        name: text
        options: 
            full_timestamp: true
            timestamp_format: "2006-01-02T15:04:05.000"
