#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.17

pipelines:
  default:
    - step:          
        name: Install protoc
        script:
          - apt update && apt install -y protobuf-compiler
    - step:          
        name: Install librkafka
        script:
          - make install/librkafka
    - step:          
        name: Prepare TF proto
        script:
          - make generate/proto
    - step:          
        name: Prepare test mocks
        script:
          - make generate/mocks     
    - step:          
        name: Build
        script:
          - make test/unit
    - step:          
        name: Lint
        script:
          - make test/lint
    