#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.17

pipelines:
  default:
    - step:          
        name: Prepare TF proto
        script:
          - cd build && ./prepareTFProto.sh
    - step:          
        name: Build
        script:
          - make test/unit      
    