   
kafka:
    brokers: aserver:9092
    group: gr1
    topic: test    
    resultTopic: results  
    
jobs: 4

fs:
    url: http://127.0.0.1:9000

logger:
    level: debug
    formatter:
        name: text
        options: 
            full_timestamp: true
            timestamp_format: "2006-01-02T15:04:05.000"
