worker:
    taskName: AudioConvert
    command: make preparedAudio/{ID}
    workingDir: /

messageServer: 
    broker: redis://localhost:6379
    defaultQueue: tasks
    resultBackend: redis://localhost:6379

logger:
    level: info
    formatter:
        name: text
        options: 
            full_timestamp: true
            timestamp_format: "2006-01-02T15:04:05.000"
